### ISSUE TITLE
XAMARIN - System.IO.FileNotFoundException: Could not load file or assembly 'PCLStorage.Abstractions' 

### ISSUE THREAD

**Issue by riccardo91** [adjust/windows_sdk#27]
Already reinstalled the library
here error log:
 [Adjust]e ActionQueue adjust.ActivityQueue with exception (System.IO.FileNotFoundException: Could not load file or assembly 'PCLStorage.Abstractions, Version=1.0.2.0, Culture=neutral, PublicKeyToken=286fe515a2c35b64' or one of its dependencies. The system cannot find the file specified.

 [Adjust]e File name: 'PCLStorage.Abstractions, Version=1.0.2.0, Culture=neutral, PublicKeyToken=286fe515a2c35b64'

 [Adjust]e    at AdjustSdk.Pcl.Util.DeserializeFromFileAsync[T](String fileName, Func`2 ObjectReader, Func`1 defaultReturn, String objectName)

 [Adjust]e    at AdjustSdk.Pcl.ActivityHandler.ReadAttribution()

 [Adjust]e    at AdjustSdk.Pcl.ActivityHandler.InitInternal(AdjustConfig adjustConfig, DeviceUtil deviceUtil)

 [Adjust]e    at AdjustSdk.Pcl.ActivityHandler.<>c__DisplayClass69_0.<.ctor>b__0()

 [Adjust]e    at AdjustSdk.Pcl.ActionQueue.ProcessTaskQueue())

**Comment by uerceg** [comment]
Hi @riccardo91 

Can you tell me which environment are you using for Xamarin development? Xamarin Studio, Visual Studio or maybe something else?

And you are using our Windows SDK for your Xamarin app?

Cheers

**Comment by uerceg** [comment]
@riccardo91 

Any update on this one maybe?

**Comment by Obaied** [comment]
Closing this for inactivity. Feel free to reopen if necessary.
